// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x4f, 0x84, 0x30,
	0x10, 0xc5, 0x25, 0x59, 0x17, 0x76, 0xd4, 0x68, 0x7a, 0x30, 0x44, 0x2f, 0x86, 0x83, 0xf1, 0x44,
	0x36, 0x7a, 0xf5, 0x0f, 0xae, 0xba, 0x68, 0x02, 0x09, 0x81, 0x83, 0xe7, 0xca, 0x4e, 0x76, 0x49,
	0x0a, 0xad, 0x6d, 0x51, 0xfb, 0x7d, 0xfd, 0x20, 0x06, 0xe2, 0x46, 0x0e, 0x9e, 0xca, 0x6d, 0x06,
	0xde, 0xfc, 0xfa, 0xfa, 0x9a, 0x81, 0xa3, 0x0d, 0x32, 0xc6, 0x3f, 0xb9, 0x64, 0xab, 0x50, 0x48,
	0xae, 0x39, 0x81, 0xbf, 0x2f, 0x41, 0x00, 0xfb, 0xcf, 0x5d, 0x97, 0xe3, 0x7b, 0x8b, 0x4a, 0x13,
	0x02, 0x93, 0x86, 0xd6, 0xe8, 0x3b, 0x67, 0xce, 0xc5, 0x2c, 0xef, 0xeb, 0xe0, 0x1c, 0xe0, 0x57,
	0x23, 0x98, 0x21, 0x3e, 0xb8, 0x35, 0x2a, 0x45, 0xd7, 0x5b, 0xd1, 0xb6, 0xbd, 0xfc, 0x9e, 0x82,
	0x1b, 0x4b, 0x44, 0x8d, 0x92, 0x44, 0xe0, 0x15, 0xd4, 0xf4, 0x63, 0xc4, 0x0f, 0x07, 0x16, 0x86,
	0xa7, 0x9d, 0x1c, 0xff, 0xf3, 0x47, 0x30, 0x13, 0xec, 0xcc, 0x1d, 0x72, 0x0f, 0xb3, 0x82, 0x9a,
	0x1c, 0x05, 0x52, 0x3d, 0x0a, 0x11, 0x73, 0xa5, 0x2a, 0x61, 0x89, 0x88, 0xc0, 0x7b, 0x69, 0xb4,
	0xe4, 0x59, 0x6b, 0x6b, 0xe2, 0x16, 0xa6, 0x05, 0x35, 0xf6, 0xf3, 0x11, 0x78, 0x09, 0xd2, 0x15,
	0xca, 0x44, 0x59, 0x12, 0x6e, 0x60, 0x37, 0x35, 0x31, 0x8e, 0x48, 0x71, 0x89, 0xba, 0xdc, 0x2c,
	0x2b, 0x86, 0xf6, 0x77, 0x48, 0xcd, 0x23, 0x32, 0xd4, 0xb6, 0x84, 0x07, 0xd8, 0x4b, 0x78, 0x49,
	0xd9, 0x28, 0xc8, 0x35, 0x4c, 0x52, 0x63, 0x1d, 0xe3, 0x1d, 0xb8, 0x59, 0xab, 0x47, 0xa4, 0xf0,
	0x04, 0x07, 0xfd, 0x3b, 0x7c, 0xa0, 0x54, 0x15, 0x6f, 0x2c, 0x7d, 0x2c, 0xe6, 0x70, 0x5a, 0xf1,
	0x70, 0x2d, 0x45, 0x19, 0xe2, 0x17, 0xad, 0x05, 0x43, 0x35, 0x50, 0x2f, 0x0e, 0x7b, 0xf9, 0x6b,
	0x57, 0x67, 0xdd, 0xba, 0x67, 0xce, 0xdb, 0xb4, 0xdf, 0xfb, 0xab, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd7, 0xec, 0x15, 0xdc, 0x0b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloClient, error)
	SayRepeat(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayRepeatClient, error)
	SayGossip(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayGossipClient, error)
	IntroPut(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_IntroPutClient, error)
	SayPut(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayPutClient, error)
	LeaderLs(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_LeaderLsClient, error)
	MyGet(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyGetClient, error)
	FetchFile(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_FetchFileClient, error)
	MyDelete(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyDeleteClient, error)
	LocalDelete(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_LocalDeleteClient, error)
	MyLs(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyLsClient, error)
	PutFile(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_PutFileClient, error)
	MyGetversions(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyGetversionsClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/helloworld.Greeter/SayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayRepeat(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayRepeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[1], "/helloworld.Greeter/SayRepeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayRepeatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayRepeatClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayRepeatClient struct {
	grpc.ClientStream
}

func (x *greeterSayRepeatClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayGossip(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayGossipClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[2], "/helloworld.Greeter/SayGossip", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayGossipClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayGossipClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayGossipClient struct {
	grpc.ClientStream
}

func (x *greeterSayGossipClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) IntroPut(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_IntroPutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[3], "/helloworld.Greeter/IntroPut", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterIntroPutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_IntroPutClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterIntroPutClient struct {
	grpc.ClientStream
}

func (x *greeterIntroPutClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayPut(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayPutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[4], "/helloworld.Greeter/SayPut", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayPutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayPutClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayPutClient struct {
	grpc.ClientStream
}

func (x *greeterSayPutClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) LeaderLs(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_LeaderLsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[5], "/helloworld.Greeter/LeaderLs", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterLeaderLsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_LeaderLsClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterLeaderLsClient struct {
	grpc.ClientStream
}

func (x *greeterLeaderLsClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) MyGet(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyGetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[6], "/helloworld.Greeter/MyGet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterMyGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_MyGetClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterMyGetClient struct {
	grpc.ClientStream
}

func (x *greeterMyGetClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) FetchFile(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_FetchFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[7], "/helloworld.Greeter/FetchFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterFetchFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_FetchFileClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterFetchFileClient struct {
	grpc.ClientStream
}

func (x *greeterFetchFileClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) MyDelete(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyDeleteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[8], "/helloworld.Greeter/MyDelete", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterMyDeleteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_MyDeleteClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterMyDeleteClient struct {
	grpc.ClientStream
}

func (x *greeterMyDeleteClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) LocalDelete(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_LocalDeleteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[9], "/helloworld.Greeter/LocalDelete", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterLocalDeleteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_LocalDeleteClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterLocalDeleteClient struct {
	grpc.ClientStream
}

func (x *greeterLocalDeleteClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) MyLs(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyLsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[10], "/helloworld.Greeter/MyLs", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterMyLsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_MyLsClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterMyLsClient struct {
	grpc.ClientStream
}

func (x *greeterMyLsClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) PutFile(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_PutFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[11], "/helloworld.Greeter/PutFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterPutFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_PutFileClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterPutFileClient struct {
	grpc.ClientStream
}

func (x *greeterPutFileClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) MyGetversions(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_MyGetversionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[12], "/helloworld.Greeter/MyGetversions", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterMyGetversionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_MyGetversionsClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterMyGetversionsClient struct {
	grpc.ClientStream
}

func (x *greeterMyGetversionsClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(*HelloRequest, Greeter_SayHelloServer) error
	SayRepeat(*HelloRequest, Greeter_SayRepeatServer) error
	SayGossip(*HelloRequest, Greeter_SayGossipServer) error
	IntroPut(*HelloRequest, Greeter_IntroPutServer) error
	SayPut(*HelloRequest, Greeter_SayPutServer) error
	LeaderLs(*HelloRequest, Greeter_LeaderLsServer) error
	MyGet(*HelloRequest, Greeter_MyGetServer) error
	FetchFile(*HelloRequest, Greeter_FetchFileServer) error
	MyDelete(*HelloRequest, Greeter_MyDeleteServer) error
	LocalDelete(*HelloRequest, Greeter_LocalDeleteServer) error
	MyLs(*HelloRequest, Greeter_MyLsServer) error
	PutFile(*HelloRequest, Greeter_PutFileServer) error
	MyGetversions(*HelloRequest, Greeter_MyGetversionsServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHello(m, &greeterSayHelloServer{stream})
}

type Greeter_SayHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayRepeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayRepeat(m, &greeterSayRepeatServer{stream})
}

type Greeter_SayRepeatServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayRepeatServer struct {
	grpc.ServerStream
}

func (x *greeterSayRepeatServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayGossip_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayGossip(m, &greeterSayGossipServer{stream})
}

type Greeter_SayGossipServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayGossipServer struct {
	grpc.ServerStream
}

func (x *greeterSayGossipServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_IntroPut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).IntroPut(m, &greeterIntroPutServer{stream})
}

type Greeter_IntroPutServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterIntroPutServer struct {
	grpc.ServerStream
}

func (x *greeterIntroPutServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayPut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayPut(m, &greeterSayPutServer{stream})
}

type Greeter_SayPutServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayPutServer struct {
	grpc.ServerStream
}

func (x *greeterSayPutServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_LeaderLs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).LeaderLs(m, &greeterLeaderLsServer{stream})
}

type Greeter_LeaderLsServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterLeaderLsServer struct {
	grpc.ServerStream
}

func (x *greeterLeaderLsServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_MyGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).MyGet(m, &greeterMyGetServer{stream})
}

type Greeter_MyGetServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterMyGetServer struct {
	grpc.ServerStream
}

func (x *greeterMyGetServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).FetchFile(m, &greeterFetchFileServer{stream})
}

type Greeter_FetchFileServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterFetchFileServer struct {
	grpc.ServerStream
}

func (x *greeterFetchFileServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_MyDelete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).MyDelete(m, &greeterMyDeleteServer{stream})
}

type Greeter_MyDeleteServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterMyDeleteServer struct {
	grpc.ServerStream
}

func (x *greeterMyDeleteServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_LocalDelete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).LocalDelete(m, &greeterLocalDeleteServer{stream})
}

type Greeter_LocalDeleteServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterLocalDeleteServer struct {
	grpc.ServerStream
}

func (x *greeterLocalDeleteServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_MyLs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).MyLs(m, &greeterMyLsServer{stream})
}

type Greeter_MyLsServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterMyLsServer struct {
	grpc.ServerStream
}

func (x *greeterMyLsServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).PutFile(m, &greeterPutFileServer{stream})
}

type Greeter_PutFileServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterPutFileServer struct {
	grpc.ServerStream
}

func (x *greeterPutFileServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_MyGetversions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).MyGetversions(m, &greeterMyGetversionsServer{stream})
}

type Greeter_MyGetversionsServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterMyGetversionsServer struct {
	grpc.ServerStream
}

func (x *greeterMyGetversionsServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello",
			Handler:       _Greeter_SayHello_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayRepeat",
			Handler:       _Greeter_SayRepeat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayGossip",
			Handler:       _Greeter_SayGossip_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IntroPut",
			Handler:       _Greeter_IntroPut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayPut",
			Handler:       _Greeter_SayPut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LeaderLs",
			Handler:       _Greeter_LeaderLs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MyGet",
			Handler:       _Greeter_MyGet_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchFile",
			Handler:       _Greeter_FetchFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MyDelete",
			Handler:       _Greeter_MyDelete_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LocalDelete",
			Handler:       _Greeter_LocalDelete_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MyLs",
			Handler:       _Greeter_MyLs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFile",
			Handler:       _Greeter_PutFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MyGetversions",
			Handler:       _Greeter_MyGetversions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
